services:
  scheduler:
    volumes:
      - ./dbt/airflow_dbt_data_warehouse/dbt_dw:/usr/local/airflow/dbt/dbt_dw
  
  dag-processor:
    volumes:
      - ./dbt/airflow_dbt_data_warehouse/dbt_dw:/usr/local/airflow/dbt/dbt_dw
